<?php

use Illuminate\Database\Seeder;

class seederJubilaciones extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*$dato = array( 
       	array('1','Empleado'),
  		array('2','Obrero'),
  		array('3','Mixta')

        );
       	foreach ($dato as $v) {
        DB::table('nominas')->insert([
           'id' => $v[0],
           'nomina_tipo' => $v[1],

          ]); 
    	}*/

    	/*$dato1 = array( 
		  array('1', 'Salud','1'),
		  array('2', 'Reestructuración','1'),
		  array('3', 'Supresión de Organismo','1'),
		  array('4', 'Avanzada Edad','1'),
		  array('5', 'Renov. Cuadros Gerenciales','1'),
		  array('6', 'Nombramiento','1'),
		  array('7', 'Designación de Funcionario','1'),
		  array('8', 'Social','1'),
		  array('9', 'Solicitud Particular','1')

        );
       	foreach ($dato1 as $v) {
        DB::table('motivos')->insert([
           'id' => $v[0],
           'nombre_motivo' => $v[1],
           'id_user' => $v[2],

          ]); 
    	}*/

    	$dato2 = array( 
		  array('1', 'Ministerios','1'),
		  array('2', 'Gobernaciones','1'),
		  array('3', 'Alcaldías','1'),
		  array('4', 'Instituto ','1'),
		  array('5', 'Fundaciones','1'),
		  array('6', 'Entes Adscritos','1'),
		  array('7', 'Empresas del Estado','1'),
		  array('8', 'Contralorias','1'),
		  array('9', 'Procuradurias','1'),
		  array('10', 'Consejos Legislativos','1'),
		  array('11', 'Corporaciones','1'),
		  array('12', 'Cabildos','1'),
		  array('13', 'Contraloría Municipal de Araure','1' ),
		  array('14', 'Consejo Municipal de Turen','1'),
		  array('15', 'Gobernación','1')

        );
       	foreach ($dato2 as $v) {
        DB::table('category_entities')->insert([
           'id' => $v[0],
           'category' => $v[1],
           'user_id' => $v[2],

          ]); 
    	}

       
        DB::table('status')->insert([
		  array('id' => '0','name' => 'En trámite'),
		  array('id' => '1','name' => 'Aprobado'),
		  array('id' => '2','name' => 'Negado'),
		  array('id' => '3','name' => 'Diferido')
          ]); 
    	

    	

		$dato4 = array( 
		  array('1', 'Instituto Autónomo Biblioteca Nacional y de Servicios de Bibliotecas (IABNSB)', '6', '1'),
		  array('2', 'Contraloria General del estado Cojedes', '8', '1'),
		  array('3', 'C.V.G Ferrominera Orinoco C.A', '7', '1'),
		  array('4', 'Instituto Agrario Nacional (IAN)', '6', '1'),
		  array('5', 'Ministerio del Poder Popular para la Planificación y Desarrollo', '1', '1'),
		  array('6', 'Vicepresidencia de la República Bolivariana de Venezuela', '6', '1'),
		  array('7', 'Instituto Venezolano de los Seguros Sociales (IVSS)', '6', '1'),
		  array('8', 'Diques y Astilleros Nacionales, C.A. (DIANCA)', '4', '1'),
		  array('9', 'Hospital Universitario de Caracas', '6', '1'),
		  array('10', 'Fundación  para el Desarrollo de la Ciencia y Tecnología del  Edo Mérida,(FUNDACITE)', '5', '1'),
		  array('11', 'Ministerio del Poder Popular para la  Infraestructura (MINFRA)', '1', '1'),
		  array('12', 'Fondo Nacional Para Edificaciones Penitenciarias (FONEP)', '6', '1'),
		  array('13', 'Compañía Anónima Venezolana de Industrias Militares (CAVIN)', '6', '1'),
		  array('14', 'Instituto Postal Telegráfico de Venezuela (IPOSTEL)', '6', '1'),
		  array('15', 'Ministerio del Poder Popular para la Salud ', '1', '1'),
		  array('16', 'Ministerio del Poder Popular para las Industrias Ligeras y Comercio', '1', '1'),
		  array('17', 'C.V.G. Internacional C.A.', '7', '1'),
		  array('18', 'Servicio Estadal de Atención al Menor del estado Lara', '6', '1'),
		  array('19', 'INDECU', '6', '1'),
		  array('20', 'Instituto Nacional de Canalizaciones', '6', '1'),
		  array('21', 'Servicio Nacional Integrado de Administración Aduanera y Tributaria (SENIAT)', '6', '1'),
		  array('22', 'Contraloria del estado Falcón', '8', '1'),
		  array('23', 'Fundación para el Desarrollo de la Región Centro Occidental de Venezuela (FUDECO)', '5', '1'),
		  array('24', 'Ministerio del Poder Popular para la Energía y Petróleo', '1', '1'),
		  array('25', 'Banco Industrial de Venezuela C.A.', '6', '1'),
		  array('26', 'Ministerio del Poder Popular para la  Defensa', '1', '1'),
		  array('27', 'Corporación Venezolana de Guayana', '6', '1'),
		  array('28', 'Fundación Teresa Carreño', '5', '1'),
		  array('29', 'Fundaciòn Josè Felix Ribas', '5', '1'),
		  array('30', 'Ministerio del Poder Popular para la Educaciòn', '1', '1'),
		  array('31', 'Fundación Instituto de Ingeniería', '5', '1'),
		  array('32', 'Fondo de Credito industrial (FONCREI)', '4', '1'),
		  array('33', 'C.A. Hidrologica del Centro', '7', '1'),
		  array('34', 'Ministerio del Poder Popular para la Educación Superior', '1', '1'),
		  array('35', 'Servicio de Atención al Menor (SEAM LARA)', '6', '1'),
		  array('37', 'Gobernación del  estado Bolívar', '2', '1'),
		  array('38', 'Ministerio del Poder Popular para el Ambiente', '1', '1'),
		  array('39', 'CORPOANDES', '6', '1'),
		  array('40', 'Instituto Nacional de Capacitación y Educación Socialista (INCES)', '6', '1'),
		  array('41', 'Contraloría del estado Bolivariano Miranda', '8', '1'),
		  array('42', 'Fondo de Garantía de Depósitos y Protección Bancaria (FOGADE)', '6', '1'),
		  array('43', 'CVG. Bauxilum, C.A.', '4', '1'),
		  array('44', 'Sistema Hidráulico Yacambú Quibor, C.A.', '6', '1'),
		  array('45', 'Fondo de Inversión Social de Venezuela (FONVIS)', '6', '1'),
		  array('46', 'Ministerio del Poder Popular para Economía y Finanzas', '1', '1'),
		  array('47', 'Fundaciòn de Etnomusicologia y Folklore (FUNDEF)', '5', '1'),
		  array('48', 'Instituto Nacional de Geología y Minería (INGEOMIN)', '6', '1'),
		  array('49', 'Ministerio del Poder Popular para la Alimentación', '1', '1'),
		  array('50', 'Contraloría del estado Portuguesa', '8', '1'),
		  array('51', 'Instituto Nacional de Nutrición', '6', '1'),
		  array('53', 'C.A. Hidrologica de la Cordillera Andina (HIDROANDES)', '7', '1'),
		  array('54', 'Fundación de Capacitación e Innovaciòn para el Desarrollo Rural (CIARA)', '5', '1'),
		  array('55', 'Oficina Nacional Antidrogas (ONA)', '6', '1'),
		  array('56', 'Oficina Nacional de Presupuesto (ONAPRE)', '6', '1'),
		  array('57', 'Instituto Venezolano de Planificación (IVEPLAN)', '6', '1'),
		  array('58', 'Instituto Nacional de Investigaciones Agrícolas (INIA)', '6', '1'),
		  array('59', 'Corporación de Abastecimiento y Servicios Agrícolas, S.A. (CASA)', '11', '1'),
		  array('60', 'Instituto Nacional de Servicios Sociales (INASS)', '6', '1'),
		  array('61', 'Alcaldía del Municipio Michelena, estado Táchira', '3', '1'),
		  array('62', 'Instituto Nacional del Menor (INAM)', '4', '1'),
		  array('63', 'Superintendencia de Bancos y Otras Instituciones Financieras (SUDEBAN)', '6', '1'),
		  array('64', 'Alcaldía del Municipio Simón Planas, estado Lara', '3', '1'),
		  array('65', 'Consejo Nacional de la Cultura (CONAC)', '6', '1'),
		  array('66', 'Contraloría General del estado Vargas', '8', '1'),
		  array('67', 'Fondo Intergubernamental para la Descentralización (FIDES)', '6', '1'),
		  array('68', 'Fondo Especial de Jubilaciones y Pensiones de los Empledos Públicos', '6', '1'),
		  array('69', 'Ministerio del Poder Popular para la Agricultura y Tierras', '1', '1'),
		  array('70', 'Corporación de Desarrollo de la Región Central (CORPOCENTRO)', '6', '1'),
		  array('71', 'Petroleos de Venezuela S.A. (PDVSA)', '7', '1'),
		  array('84', 'Ministerio del  Poder Popular del Despacho de la Presidencia ', '1', '1'),
		  array('85', 'Secretaria General del Consejo de la Nación (SECODENA)', '6', '1'),
		  array('86', 'Oficina Nacional del Tesoro (ONT)', '6', '1'),
		  array('87', 'Ministerio del  Poder Popular para Relaciones Interiores y Justicia', '1', '1'),
		  array('88', 'Ministerio del  Poder Popular para  Relaciones Exteriores  MRE', '1', '1'),
		  array('89', 'Ministerio del  Poder Popular para el Trabajo y Seguridad Social  MT', '1', '1'),
		  array('90', 'Ministerio del Poder Popular para la Ciencia, Tecnología e Industrias Intermedias', '1', '1'),
		  array('91', 'Ministerio del Poder Popular para la Comunicación e Información  MINCI', '1', '1'),
		  array('92', 'Ministerio del Poder Popular para las Industrias Básicas y Minería MIBM', '1', '1'),
		  array('93', 'Ministerio del  Poder Popular para  la Cultura MC', '1', '1'),
		  array('94', 'Ministerio del Poder Popular para la Vivienda y Hábitat  MVH', '1', '1'),
		  array('95', 'Ministerio del  Poder Popular para la Economía Popular  MINEP', '1', '1'),
		  array('96', 'Ministerio de la Producción y el Comercio  MPC', '1', '1'),
		  array('97', 'Ministerio del  Poder Popular para el Turismo  MINTUR', '1', '1'),
		  array('98', 'Ministerio del  Poder Popular Para la Participación Popular y Desarrollo Social  MINPADES', '1', '1'),
		  array('99', 'Comisión Nacional Valores (C.N.V)', '6', '1'),
		  array('100', 'Consejo Nacional de Investigaciones Científicas y Tecnológicas (CONICIT)', '6', '1'),
		  array('101', 'Consejo Nacional de Universidades (CNU)', '6', '1'),
		  array('102', 'Corporación de Desarrollo de la Región Centro Occidental (CORPOOCCIDENTE)', '6', '1'),
		  array('103', 'Corporación de Desarrollo de la Región Zuliana (CORPOZULIA)', '6', '1'),
		  array('104', 'Corporación de Desarrollo de la Pequeña y Mediana Industria (CORPOINDUSTRIA)', '6', '1'),
		  array('105', 'Corporación de Desarrollo de la Región de Oriente (CORPORIENTE)', '6', '1'),
		  array('106', 'Corporación de Turismo de Venezuela (CORPOTURISMO)', '6', '1'),
		  array('107', 'Corporación Venezolana de Fomento (CVF)', '6', '1'),
		  array('108', 'Corporación de Desarrollo de la Región de los Llanos (CORPOLLANOS)', '6', '1'),
		  array('110', 'Corporación Venezolana del Suroeste (CVS)', '6', '1'),
		  array('111', 'Corporación para la Recuperación y Desarrollo del Estado Vargas (CORPOVARGAS)', '6', '1'),
		  array('112', 'Corporación Venezolana Agraria (CVA)', '6', '1'),
		  array('114', 'CORPOTULIPA : Corp. Zona Libre  Fomt. Inversión Turística en la Península de Paraguaya ', '6', '1'),
		  array('115', 'Fondo de Desarrollo Agropecuario, Pesquero, Forestal y Afines (FONDAFA)', '6', '1'),
		  array('116', 'Fondo Nacional de Desarrollo Urbano (FONDUR)', '6', '1'),
		  array('117', 'Fondo de Investigaciones Agropecuarias (FONAIAP)', '6', '1'),
		  array('118', 'Fondo Nacional del Cacao (FONCACAO)', '6', '1'),
		  array('119', 'Fondo Nacional del Café (FONCAFE)', '6', '1'),
		  array('120', 'Fondo Nacional de Ciencia, Tecnología e Innovación (FONACIT)', '6', '1'),
		  array('121', 'Instituto Autónomo de la Caja de Trabajo Penitenciario (IACTP)', '6', '1'),
		  array('122', 'Instituto Autónomo Circulo de las Fuerzas Armadas (IACFA)', '6', '1'),
		  array('124', 'Instituto Autónomo Administrativo Ferrocarriles del Estado (FERROCAR)', '6', '1'),
		  array('125', 'Instituto Autónomo Aeropuerto de Maiquetia (IAAIM)', '6', '1'),
		  array('126', 'Instituo Autónomo Biblioteca Nacional y de Serv de Bibliotecas (IABN)', '6', '1'),
		  array('127', 'Instituto Autónomo Hospital Universitario de Caracas (IAHUC)', '6', '1'),
		  array('128', 'Instituto de Comercio Exterior (ICE)', '6', '1'),
		  array('129', 'Instituto de Oficiales en Situación de Disponibilidad y Retiro (IORFAN)', '6', '1'),
		  array('130', 'Instituto de Previsión Social de las Fuerzas Armadas (IPSFA)', '6', '1'),
		  array('131', 'Instituto Nacional de Capacitación y Recreación de Trabajadores (INCRET)', '6', '1'),
		  array('132', 'Instituto Nacional de Deportes (IND)', '6', '1'),
		  array('133', 'Instituto Nacional de Geriatría y Gerontologia (INAGER)', '6', '1'),
		  array('134', 'Instituto Nacional de Hipódromos (INH)', '6', '1'),
		  array('135', 'Instituto Nacional de Obras Sanitarias (INOS)', '6', '1'),
		  array('136', 'Instituto Nacional de Parques (INPARQUES)', '6', '1'),
		  array('137', 'Instituto Nacional de Puertos (INP)', '6', '1'),
		  array('138', 'Instituto Nacional de la Vivienda (INAVI)', '6', '1'),
		  array('139', 'Instituto Municipal de Aseo Urbano(IMAU)', '6', '1'),
		  array('140', 'Instituto de Prevención Social para Empleados del Ministerio de Educación (IPASME)', '6', '1'),
		  array('141', 'Instituto Venezolano de Investigaciones Científicas (IVIC)', '6', '1'),
		  array('142', 'Instituto Para el Control y la Const de la Cuenca  de Maracaibo (ICCLAM)', '6', '1'),
		  array('143', 'Instituto para la Defensa y Educ. del Consumidor y del Usuario (INDECU)', '6', '1'),
		  array('144', 'Instituto Autónomo Consejo Nacional de la Vivienda(CONAVI)', '6', '1'),
		  array('145', 'Instituto Nacional de Estadística (I.N.E)', '6', '1'),
		  array('146', 'Ente Nacional del Gas (ENAGAS)', '6', '1'),
		  array('147', 'Instituto Geográfico Venezuela Simón Bolívar (IGVSB)', '6', '1'),
		  array('148', 'Instituto Nacional de Transito y Transporte Terrestre (INTTT)', '6', '1'),
		  array('149', 'Instituto Nacional de Desarrollo de la Pequeña y Mediana Industria (INAPYMI)', '6', '1'),
		  array('150', 'Instituto Nacional de los Espacios Acuáticos e Insulares (INEA)', '6', '1'),
		  array('151', 'Instituto Nacional de Aeronáutica Civil (INAC)', '6', '1'),
		  array('152', 'Instituto Nacional de Tierras (INTI)', '6', '1'),
		  array('153', 'Instituto Nacional de la Juventud (INJ)', '6', '1'),
		  array('154', 'Instituto Nacional de la Mujer (INAMUJER)', '6', '1'),
		  array('155', 'Instituto Nacional de Pesca y Acuicultura (INAPESCA)', '6', '1'),
		  array('156', 'Instituto Nacional del Turismo (INATUR)', '6', '1'),
		  array('157', 'Instituto Nacional de Prevención, Salud y Seguridad Laborales (INPSASEL)', '6', '1'),
		  array('158', 'Instituto Nacional de Desarrollo Rural (INDER)', '6', '1'),
		  array('159', 'Instituto Autónomo Fondo Único Social (IAFUS)', '6', '1'),
		  array('160', 'Superintendencia de Servicios de Certificación Electrónica del M.C.T (SUSCERTE)', '6', '1'),
		  array('161', 'Servicio Autónomo Ofic. Coord. de Apoyo Marítimo de la Armada (OCAMAR)', '6', '1'),
		  array('162', 'Superintendencia Nacional de Actividades Hípicas(SUNAHIP)', '6', '1'),
		  array('164', 'Comando General de la Reserva Militar y Movilización Nacional (CGRMYMN)', '1', '1'),
		  array('165', 'Procuradora Agraria Nacional (PAN)', '6', '1'),
		  array('167', 'C.A. Hidrológica del Caribe, Filial de Hidroven', '7', '1'),
		  array('170', 'CVG, Aluminio del Caroní, C.A.', '7', '1'),
		  array('173', 'Instituto Autónomo Municipal Cuerpo de Bomberos de Valencia', '4', '1'),
		  array('174', 'Consejo Estadal de Derechos del Niño y del Adolescente', '6', '1'),
		  array('175', 'Contraloría General del estado Bolívar', '8', '1'),
		  array('176', 'Gobernación del estado Falcón', '2', '1' => '269', '1217980800'),
		  array('177', 'Alcaldía del Municipio Girardot, estado  Aragua', '3', '1'),
		  array('178', 'C.V.G. VENALUM, c.a', '7', '1'),
		  array('179', 'Gobernación del estado Cojedes', '2', '1'),
		  array('180', 'Procuraduría General de la República', '9', '1'),
		  array('181', 'CVG, CABELUM, C.A.', '7', '1'),
		  array('182', 'Gobernación del estado Portuguesa', '2', '1'),
		  array('183', 'C.A. Hidrológica de los Medanos Falconianos (HIDROFALCÓN)', '7', '1'),
		  array('184', 'Fundación Centro Nacional para el Mejoramiento de la Enseñanza de la Ciencia (CENAMEC)', '6', '1'),
		  array('185', 'Consejo Legislativo del estado Falcón', '10', '1'),
		  array('186', 'Procuraduría General del estado Mérida', '9', '1'),
		  array('187', 'Alcaldía del Municipio Zea, estado Mérida', '3', '1'),
		  array('188', 'Alcaldía del Municipio Vargas, estado Vargas', '3', '1'),
		  array('189', 'Corporación de Salud del Estado Aragua', '6', '1' ),
		  array('190', 'Servicio Autónomo Imprenta Nacional y Gaceta Oficial', '6', '1'),
		  array('191', 'Contraloría del Municipio Michelena, estado Táchira', '8', '1'),
		  array('192', 'Fundación Fondo Nacional de Transporte Urbano (FONTUR)', '5', '1'),
		  array('193', 'Instituto Autónomo  de Aeropuertos del Estado Falcón', '4', '1'),
		  array('194', 'C.V.G. Aluminio del Caroní, C.A.', '7', '1'),
		  array('195', 'Fundación Poliedro de Caracas', '5', '1'),
		  array('196', 'Fundación Museos Nacionales (Museo de Bellas Artes)', '5', '1'),
		  array('197', 'Alcaldía del Municipio Arzobispo Chacón, estado Mérida', '3', '1'),
		  array('198', 'Corporación Falconiana de Turismo(CORFALTUR)', '11', '1'),
		  array('199', 'C.A. Hidrológica de la Región Capital (HIDROCAPITAL)', '6', '1'),
		  array('200', 'Fundación Misión Sucre', '5', '1'),
		  array('202', 'C.A. Hidrológica del Centro (HIDROCENTRO)', '7', '1'),
		  array('203', 'Alcaldía del Municipio Catatumbo, estado Zulia', '3', '1'),
		  array('204', 'Alcaldía del Municipio Monseñor José Vicente de Unda, estado Portuguesa', '3', '1'),
		  array('205', 'C.V.G. BAUXILUM, C.A.', '7', '1'),
		  array('206', 'Alcaldía del Municipio Carvajal, estado Anzoátegui', '3', '1'),
		  array('209', 'Fundación Cinemateca Nacional', '5', '1'),
		  array('210', 'Contraloría Metropolitana de Caracas', '8', '1' ),
		  array('211', 'Fundación para el Desarrollo del Estado Táchira (FUNDATÁCHIRA)', '5', '1' ),
		  array('212', 'Instituto de Vialidad del Estado Falcón (INVIALFA)', '4', '1' ),
		  array('213', 'Banco de Desarrollo Económico y Social de Venezuela (BANDES)', '6', '1' ),
		  array('214', 'Agencia Bolivariana de Noticias', '6', '1'),
		  array('215', 'C.V.G. Productos Forestales de Oriente C.A. (C.V.G. PROFORCA)', '7', '1'),
		  array('216', 'Servicio Autónomo de Sanidad Agropecuaria (S.A.S.A.)', '6', '1'),
		  array('217', 'Servicio Autónomo de Sanidad Agropecuaria (SASA)', '6', '1' ),
		  array('218', 'Contraloría General del estado Guárico', '8', '1' ),
		  array('219', 'Contraloría del estado Aragua ', '8', '1' ),
		  array('220', 'Alcaldía del Municipio Libertad Capacho Viejo, estado Táchira', '3', '1' ),
		  array('221', 'Fundación Instituto de Estudios Avanzados (IDEA)', '5', '1' ),
		  array('222', 'Alcaldía  del Distrito Metropolitano de Caracas', '3', '1' ),
		  array('223', 'Alcaldía Municipio Libertador, Temblador estado Monágas ', '3', '1' ),
		  array('224', 'Alcaldía del Municipio Baruta ', '3', '1' ),
		  array('225', 'Mnisterio del Poder Popular para las Obras Públicas y Vivienda (MOPVI)', '1', '1'),
		  array('226', 'Contraloría del estado Barinas', '8', '1' ),
		  array('227', 'Contraloría del estado Monagas', '8', '1' ),
		  array('228', 'Cabildo del Distrito Metropolitano de Caracas', '12', '1' ),
		  array('229', 'Fundación para la Cultura y las Artes (FUNDARTE)', '5', '1' ),
		  array('230', 'Contraloría Municipal de Girardot, estado Aragua ', '8', '1' ),
		  array('231', 'Fundación Museos Nacionales (Museo de Ciencias)', '5', '1'),
		  array('232', 'Fundación de Edificaciones y Dotaciones Educativas (FEDE)', '5', '1' ),
		  array('233', 'Fundación Guarderia Infantil La Alquitrana', '6', '1' ),
		  array('234', 'Aguas de Monagas', '6', '1' ),
		  array('235', 'C.V.G. MINERVEN, C.A.', '7', '1'),
		  array('236', 'Instituto de Ferrocarriles del Estado (IFE)', '6', '1' ),
		  array('237', 'Ministerio del Poder Popular de Planificación y Finanzas', '1', '1' ),
		  array('238', 'Contraloria Municipal del Municipio Sucre, estado Yaracuy', '8', '1'),
		  array('239', 'Consejo Legislativo del estado Aragua', '10', '1'),
		  array('240', 'Fundación para el Desarrollo de la Ciencia y la Tecnología FUNDACITE-ZULIA', '5', '1'),
		  array('241', 'Contraloría Municipal del Municipio Bolivariano Libertador, Distrito Capital', '8', '1'),
		  array('242', 'Superintendencia Nacional de Auditoría Interna (SUNAI)', '6', '1'),
		  array('243', 'Consejo Legislativo del estado Bolivariano de Miranda', '10', '1'),
		  array('244', 'Servicio Bolivariano de Inteligencia Nacional (SEBIN)', '6', '1'),
		  array('245', 'Instituto de Vivienda Obras y Servicios del Estado Bolívar, (INVIOBRAS Bolívar)', '4', '1'),
		  array('246', 'Fundación Museos Nacionales (Museo Arte Contemporaneo)', '5', '1'),
		  array('247', 'Oficina Nacional de Crédito Público (ONCP)', '6', '1'),
		  array('248', 'Oficina Nacional de Contabilidad Pública (ONCOP)', '6', '1'),
		  array('249', 'Banco de Comercio Exterior (BANCOEX)', '6', '1'),
		  array('250', 'Fundación Museos Nacionales (Museo Jacobo Borges)', '5', '1'),
		  array('251', 'Alcaldía Bolivariana del Municipio Los Taques, estado Falcón', '3', '1' ),
		  array('252', 'Contraloría Municipal Francisco de Miranda, estado Guárico', '8', '1' ),
		  array('253', 'Procuraduria General del Estado Trujillo', '9', '1'),
		  array('254', 'Aguas de Mérida, C.A', '6', '1'),
		  array('255', 'Contraloría General de la Fuerza Armada Nacional Bolivariana', '8', '1'),
		  array('256', 'Consejo Municipal de Iribarren, estado Lara', '10', '1'),
		  array('257', 'Fondo Autonomo de Inversiones y Previsión Socio-Economica para Empleados y Obreros de la Fuerza Armada Nacional (FONDOEFA)', '5', '1'),
		  array('259', 'Arrendadora Financiera Empresarial C.A (Anfico)', '6', '1' ),
		  array('260', 'Alcaldía Bolivariana del Municipio Guásimos', '3', '1' ),
		  array('261', 'Instituto Aeropuerto Internacional de Maiquetía', '4', '1' ),
		  array('262', 'Alcaldía Bolivariana del Municipio Guásimos, estado Táchira', '3', '1'),
		  array('263', 'Alcaldía del Municipio Sucre, estado Miranda', '3', '1' ),
		  array('264', 'Contraloría del estado Anzoátegui', '8', '1'),
		  array('265', 'Banco Agrícola de Venezuela, C A', '7', '1' ),
		  array('266', 'Contraloría del estado Guárico', '8', '1' ),
		  array('268', 'Centro Simón Bolívar,  C.A.', '6', '1' ),
		  array('269', 'Banco Agrícola de Venezuela C.A.', '7', '1' ),
		  array('270', 'Sociedad Nacional de Garantías Recíprocas para la Mediana y Pequeña Industria (SOGAMPI);S.A.', '6', '1' ),
		  array('271', 'C.A. Metro Los Teques', '7', '1'),
		  array('272', 'Ministerio del Poder Popular de Petróleo y Minería', '1', '1'),
		  array('273', 'Servicio Nacional de Contrataciones (SNC)', '6', '1'),
		  array('274', 'Contraloría del estado Sucre', '8', '1'),
		  array('275', 'Instituto Autonomo de Aguas y Acueductos del Municipio Cedeño', '4', '1' ),
		  array('276', 'Alcaldía del Municipio Cedeño', '3', '1' ),
		  array('277', 'Contraloría Municipal de Chacao', '8', '1' ),
		  array('278', 'Alcaldia del Municipio Bolivariano Libertador', '3', '1' ),
		  array('279', 'C.A. Metro de Valencia', '7', '1'),
		  array('280', 'Alcaldía del Municipio Los Salias, estado Miranda', '3', '1' ),
		  array('281', 'Contraloría del estado Mérida', '8', '1' ),
		  array('282', 'Cotraloría del Municipio AmbrosioPlaza, Guarenas', '8', '1' ),
		  array('283', 'Contraloría del Municipio Ambrosio Plaza, Guarenas', '8', '1' ),
		  array('284', 'Gobernación del estado Monagas', '2', '1'),
		  array('285', 'Instituto de Cultura del Estado Falcón (INCUDEF)', '4', '1' ),
		  array('286', 'Contraloría del Municipio Turistico El Morro Licenciado Diego Bautista Urbaneja, Lecheria, estado Anzoátegui', '8', '1'),
		  array('287', 'Alcaldía Bolivariana de San Joaquín, estado Carabobo', '3', '1'),
		  array('288', 'Contraloría del estado Trujillo', '8', '1'),
		  array('289', 'Fondo Único de Crédito del Estado Barinas', '6', '1' ),
		  array('290', 'Alcaldía del  Municipio San Diego, estado Carabobo', '3', '1' ),
		  array('291', 'Fundación J.V. Seijas Aquarium de Valencia', '5', '1' ),
		  array('292', 'Corporación Apureña de Turismo (CORATUR)', '11', '1' ),
		  array('293', 'Bicentenario Banco Universal C.A.', '6', '1' ),
		  array('294', 'Consejo Legislativo del estado Carabobo', '10', '1' ),
		  array('297', 'Fundación Orquesta Sinfónica del Estado Mérida', '5', '1' ),
		  array('298', 'Alcaldía del Municipio Independencia ', '3', '1' ),
		  array('299', 'Alcaldía del Municipio Independencia Capacho Nuevo, estado Táchira', '3', '1' ),
		  array('300', 'Contraloría del estado Carabobo', '8', '1' ),
		  array('301', 'Contraloría  Municipal, Municipio Barinas', '8', '1' ),
		  array('302', 'Instituto Autónomo de la Vivienda y Equipamientos de Barrios, Estado Barinas (IAVEB) ', '4', '1' ),
		  array('303', 'HIDROBOLÍVAR C.A.', '7', '1' ),
		  array('304', 'Instituto Autónomo de Minas Bolívar', '4', '1' ),
		  array('305', 'Contraloría Municipal del Municipio Lobatera, estado Táchira', '8', '1' ),
		  array('306', 'Ministerio del Poder Popular para Relaciones Interiores, Justicia y Paz', '1', '1' ),
		  array('307', 'Fondo de Protección Social de los Depósitos Bancarios (FOGADE)', '6', '1' ),
		  array('308', 'Superintendencia de las Instituciones del Sector Bancario (SUDEBAN)', '6', '1'),
		  array('309', 'Contraloría Municipal de Araure, estado Portuguesa', '8', '1'),
		  array('310', 'Instituto de Transporte y Vialidad del Estado Barinas (INTRAVIAL)', '4', '1' ),
		  array('311', 'Empresa Nacional Salinera ENASAL', '7', '1' ),
		  array('312', 'Corporación Eléctrica Nacional - CORPOELEC', '11', '1' ),
		  array('313', 'Fundación Museos Nacionales (Galeria de Arte Nacional)', '5', '1' ),
		  array('314', 'Superintendencia de la Actividad Aseguradora', '6', '1'),
		  array('315', 'Hidrológica Venezolana,C.A. HIDROVEN', '4', '1' ),
		  array('316', 'Superintendencia Nacional de Valores', '6', '1'),
		  array('317', 'Fundación Centro de Estudios Latinoamericanos Rómulo Gallegos', '5', '1' ),
		  array('318', 'Instituto Nacional de Deporte y Recreación de Araure (IMDERA), Estado Portuguesa', '4', '1' ),
		  array('319', 'Alcadía del Municipio Iribarren, estado Lara', '3', '1' ),
		  array('320', 'Consejo Municipal del Municipio Motatan, estado Trujillo', '10', '1' ),
		  array('321', 'Consejo Municipal Independencia, estado Yaracuy', '10', '1' ),
		  array('322', 'Consejo del Municipio Jiménez, estado Lara', '10', '1' ),
		  array('323', 'Consejo Municipal de Valera, estado Trujillo', '10', '1' ),
		  array('324', 'Radio Mundial, C.A.', '6', '1'),
		  array('325', 'Radio Margarita, C.A.', '6', '1'),
		  array('326', 'Radio Zulia, C.A.', '6', '1'),
		  array('327', 'Alcaldía Socialista del Municipio Guacara, estado Carabobo', '3', '1'),
		  array('328', 'Venezolana de Teleféricos (Ventel, C.A. Edo. Mérida) ', '7', '1' ),
		  array('329', 'Ministerio del Poder Popular de Economía, Finanzas y Banca Pública', '1', '1' ),
		  array('330', 'Consejo Municipal Simón Planas,  estado Lara', '10', '1' ),
		  array('331', 'Concejo Municipal del Libertador, estado Mérida', '10', '1'),
		  array('332', 'Consejo Municipal del Municipio Piar, estado Bolívar', '10', '1'),
		  array('333', 'Corporación Portugueseña de Turismo (CORPOTUR)', '11', '1'),
		  array('334', 'Contraloría Municipal del Municipio Vargas', '8', '1' ),
		  array('335', 'Concejo Municipal, Municipio Puerto Cabello', '10', '1' ),
		  array('336', 'Fundación Centro de Estudios sobre Crecimiento y Desarrollo de la Población Venezolana (FUNDACREDESA)', '5', '1' ),
		  array('337', 'Fundación para el Desarollo de la Ciencia y la tecnología en el Estado Zulia (FUNDACEITE ZULIA)', '5', '1' ),
		  array('338', 'Fundación Misión Piar', '5', '1' ),
		  array('339', 'Instituto Municipal de Aseo Urbano y Domiciliario (IMASEO)', '4', '1' ),
		  array('340', 'Alcaldía del Municipio Bolivariano Libertador, Distrito Capital', '3', '1' ),
		  array('341', 'Instituto de Altos Estudios de Control Fiscal y Auditoría de Estado, Fundación Gumercindo xxx (COFAEN)', '4', '1' ),
		  array('342', 'Instituto de Altos Estudios de Control Fiscal y Auditoría de Estado Fundación Gumercindo Torres (COFAE)', '4', '1' ),
		  array('343', 'Fundación para el Desarrollo de la Ciencia y la Tecnología del estado Falcón (FUNDACITE, FALCÓN)', '5', '1'),
		  array('344', 'Procuraduría del Estado Bolivariano de Miranda', '9', '1' ),
		  array('345', 'Corporación Venezolana de Guayana  Venelum', '11', '1' ),
		  array('346', 'Corporación Venezolana de Guayana Venalum', '11', '1' ),
		  array('347', 'Fundación Compañia Nacional de Danza', '5', '1' ),
		  array('348', 'Concejo Municipal de Vargas.', '10', '1' ),
		  array('349', 'Fundación Instituto de Ingenieria para investigación y Desarrollo Tecnologíco', '5', '1' ),
		  array('350', 'Fundación  Escuela de Gerencia Social', '5', '1' ),
		  array('351', 'Contraloria Municipal Libertador, estado Aragua', '8', '1' ),
		  array('352', 'CVG VENALUM', '7', '1' ),
		  array('353', 'Contraloria del estado Yaracuy', '8', '1' ),
		  array('354', 'Consejo Municipal de Maracaibo', '10', '1' ),
		  array('355', 'Contraloria del Municipio José Vicente de Unda, estado Portuguesa', '8', '1' ),
		  array('356', 'Contraloria Municipal de Maturin, estado Monagas', '8', '1' ),
		  array('357', 'Gobernación del estado Bolivariano de Nueva Esparta', '2', '1' ),
		  array('358', 'Procuraduría General del estado Bolivariano de Aragua', '9', '1' ),
		  array('359', 'Instituto para la Defensa de las Personas en el Acceso a los Bienes y Servicios (INDEPABIS)', '4', '1' ),
		  array('360', 'Contraloria del Municipio Turén ', '8', '1' ),
		  array('361', 'Centro Nacional de Técnologia de Información ', '6', '1' ),
		  array('362', 'Contraloria Municipal de Mariño, estado Nueva Esparta', '8', '1' ),
		  array('363', 'Contraloria Municipal del Distrito Sucre, estado Bolivariano de Miranda', '8', '1' ),
		  array('364', 'Consejo Municipal Turen', '10', '1' ),
		  array('365', 'Consejo Municipal del Municipio Cedeño, estado Monagas ', '10', '1' ),
		  array('366', 'Contraloría del estado Lara', '8', '1' ),
		  array('367', 'Banco de Desarrollo de la Mujer, C.A.  BANMUJER C.A.', '7', '1' ),
		  array('368', 'Instituto Nacional de Estadistica (INE)', '4', '1' ),
		  array('369', 'Contraloría del Municipio San Rafael de Carvajal, estado Trujillo', '8', '1' ),
		  array('370', 'Alcaldía del Municipio Chacao', '3', '1' ),
		  array('371', 'Procuraduría General del estado Sucre', '9', '1' ),
		  array('372', 'Fundación Laboratorios de Vialidad (FUNDALANAVIAL)', '5', '1' ),
		  array('373', 'Contraloría Municipal, Municipio Sucre, estado Bolivariano de Miranda', '8', '1' ),
		  array('374', 'Gobierno del Distrito Capital (Protección Civil)', '2', '1' ),
		  array('375', 'Instituto Autónomo Consejo Nacional de Derechos de Niños, Niñas y Adolescentes (IDENNA)', '4', '1' ),
		  array('376', 'Corporación Venezolana de Telecomunicaciones, S.A.', '11', '1' ),
		  array('377', 'Ministerio del Poder Popular para Ecosocialismo, Hábitat y Vivienda', '1', '1' ),
		  array('379', 'Consejo Nacional de Universidades Oficina de Planificación del Sector Universitario (CNU-OPSU)', '6', '1' ),
		  array('380', 'Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología', '1', '1' ),
		  array('382', 'Contraloría Municipal de Iribarren, estado Lara', '8', '1' ),
		  array('383', 'Fundación Pueblo Soberano', '5', '1' ),
		  array('384', 'Contraloría Municipal del Municipio Baruta, estado Bolivariano de Miranda', '8', '1' ),
		  array('385', 'Fundación Propatria 2000', '5', '1' ),
		  array('386', 'Ministerio del Poder Popular de Economía y Finanzas', '1', '1' ),
		  array('387', 'Instituto Autónomo Policía Municipal del Municipio Los Salias', '4', '1' ),
		  array('388', 'Contraloría Municipal Municipio Simón Bolivar, estado Anzoategui', '8', '1' ),
		  array('389', 'Comisión Nacional de Telecomunicaciones (Conatel)', '7', '1' ),
		  array('390', 'Ministerio del Poder Popular de Planificación', '1', '1' ),
		  array('391', 'Agencia Venezolana de Noticias, C.A', '7', '1' ),
		  array('392', 'Alcaldía del Municipio Uracoa estado Monagas', '3', '1' ),
		  array('393', 'Ministerio del Poder Popular para el Proceso Social de Trabajo', '1', '1' ),
		  array('394', 'Contraloría estado Delta Amacuro', '8', '1' ),
		  array('395', 'Instituto Autónomo para el Desarrollo de la Economía Social del estado Táchira (FUNDESTA)', '4', '1' ),
		  array('396', 'Banco Bicentenario del Pueblo, de la Clase Obrera, Mujer y Comunas Banco Universal, C.A.', '7', '1' ),
		  array('397', 'Consejo Legislativo del estado Vargas', '10', '1' ),
		  array('398', 'Fundación Centro de la Diversidad Cultural', '5', '1' ),
		  array('399', 'Ministerio del Poder Popular para Transporte Terrestre y Obras Públicas', '1', '1' ),
		  array('400', 'Instituto de la Cultura del Estado Monagas', '4', '1' ),
		  array('401', 'Fundación Complejo Cultural de Maturin', '5', '1' ),
		  array('402', 'Consejo Municipal de Carirubana', '10', '1' ),
		  array('403', 'Superintendencia de Precios Justos (SUNDECOP)', '6', '1' ),
		  array('404', 'Concejo Bolivariano del Municipio los Taques', '10', '1' ),
		  array('405', 'Contraloría Municipal del Municipio Carirubana', '8', '1' ),
		  array('406', 'Fundación para el Desarrollo del Servicio Eléctrico (FUNDELEC)', '5', '1' ),
		  array('407', 'Concejo Municipal Libertador, estado Carabobo', '10', '1' ),
		  array('408', 'Contraloría del estado Bolivariano de Nueva Esparta', '8', '1' ),
		  array('410', 'Fundación para el Fomento y Desarrollo de Obras y Actividades Turisticas y Recreacionales (FUNDATUR)', '5', '1' ),
		  array('412', 'Tesorería de Seguridad Social', '6', '1' ),
		  array('416', 'Fundación Museos Nacionales (Museo de Arte Popular)', '5', '1' ),
		  array('418', 'Contraloría del Municipio Ambrosio Plaza, Guarenas. Estado Miranda', '8', '1' ),
		  array('419', 'Gobernación del Estado Barinas', '2', '1' ),
		  array('420', 'Instituto para el Control y la Conservación de la Cuenca del Lago de Maracaibo (ICLAM)', '4', '1' ),
		  array('421', 'Ministerio del Poder Popular para Habitat y Vivienda', '1', '1' ),
		  array('422', 'Contraloría Municipal de Baruta', '8', '1' ),
		  array('423', 'Consejo Municipal del Municipio Vargas del estado Vargas ', '14', '1' ),
		  array('424', 'Concejo Municipal del Municipio Vargas del Estado Vargas', '14', '1'),
		  array('425', 'Fundación Museos Nacionales (Museo de Arte Valencia)', '5', '1' ),
		  array('426', 'Ministerio del Poder Popular para la Juventud y el Deporte', '1', '1' ),
		  array('427', 'Contraloría del Estado Bolivariano de Miranda', '8', '1' ),
		  array('428', 'Alcaldia del Municipio Valencia, edo Carabobo', '3', '1' ),
		  array('429', 'Contraloría Municipal del Municipío Bolivariano de Guaícaipuro ', '8', '1' ),
		  array('430', 'Alcaldía del Municipio San Joaquín, estado Carabobo. ', '3', '1' ),
		  array('431', 'Instituto Autonómo de Policía Municipal Los Salias, estado Bolivariano de Miranda.', '4', '1' ),
		  array('432', 'Contraloría Municipal del Municipio Bolivariano de Guaicaipuro, estado Miranda.', '8', '1' ),
		  array('434', 'Fundación Centro Nacional para el Mejoramiento de la Enseñanza de la Ciencia (CENAMEC)', '5', '1' ),
		  array('435', 'Fundación Museos Nacionales (Sede)', '5', '1' ),
		  array('436', 'Fundación Museos  Nacionales (Museo de Estampa y el Diseño Carlos Cruz Diez) ', '5', '1' ),
		  array('437', 'Contraloría del estado Bolivariano de Aragua', '8', '1' ),
		  array('438', 'Contraloria Municipio Pedraza, estado Barinas', '8', '1' ),
		  array('439', 'Ministerio del Poder Popular para la Banca y Finanzas', '1', '1' ),
		  array('440', 'Contraloría Municipal de Puerto Cabello ', '8', '1'),
		  array('441', 'Contraloría Municipio Maneiro, Estado Nueva Esparta', '8', '1'),
		  array('442', 'Consejo Municipal de San Diego, edo Carabobo', '10', '1'),
		  array('443', 'Consejo Legislativo del Estado Barinas', '10', '1'),
		  array('444', 'Fundación Casa del Artista', '5', '1'),
		  array('445', 'Red de Abastos Bicentenario, S.A', '7', '1'),
		  array('446', 'Instituto de Deportes del estado Bolivar', '4', '1'),
		  array('447', 'Ministerio del Poder Popular para la Energía Eléctrica (M.P.P.E.E)', '1', '1'),
		  array('448', 'Concejo Municipal Municipio Los Salias', '10', '1'),
		  array('449', 'Instituto Autonomo de aguas y acueductos de Sucre (IMAS)', '4', '1'),
		  array('450', 'Contraloria Municipal Mario Briceño Iragorry', '8', '1'),
		  array('452', 'Consejo Legislativo del Estado Zulia', '10', '1'),
		  array('453', 'Corporación de Abastecimiento y Servicios Agrícolas, S.A.', '4', '1'),
		  array('454', 'Contraloría del estado Zulia', '8', '1'),
		  array('455', 'Contraloria Municipal del Municipio Los Salias', '8', '1'),
		  array('456', 'Ministerio del Poder Popular del Despacho de la Presidencia y Seguimiento de la Gestión de Gobierno', '1', '1'),
		  array('457', 'Corporacion venezolana de alimentos CVAL S.A', '11', '1'),
		  array('458', 'Contraloría Municipal Municipio Sucre Estado Bolivariano de Miranda', '8', '1'),
		  array('459', 'Alcaldia del Municipio Los Taques', '3', '1'),
		  array('460', 'Fundación Museos Nacionales (Museo de Ciencia y Tecnología)', '5', '1'),
		  array('461', 'Fundación Programa de Alimentos Estratégicos (FUNDAPROAL)', '5', '1'),
		  array('462', 'Ministerio del Poder Popular para el Ecosocialismo y Aguas', '1', '1'),
		  array('463', 'Contraloria del Estado Bolivariano de Guárico', '8', '1'),
		  array('464', 'concejo del municipio bolivariano libertador', '10', '1'),
		  array('465', 'Concejo del Municipio Libertador', '10', '1'),
		  array('466', 'Concejo Municipal Bolivariano Libertador ', '10', '1'),
		  array('467', 'Instituto Autónomo Municipal de Tránssito y Transporte Público Urbano de Pasajero', '4', '1'),
		  array('468', 'Fundación Museos Nacionales (Sede Central)', '5', '1'),
		  array('469', 'CORPOLARA', '11', '1'),
		  array('470', 'Contraloría Municipal Municipio Barinas', '8', '1'),
		  array('472', 'Ministerio del Poder Popular de Petróleo', '1', '1'),
		  array('473', 'Contraloría del estado Bolivariano de Mérida', '8', '1'),
		  array('474', 'Servicio Nacional de Medicina y Ciencias Forenses', '4', '1'),
		  array('475', 'CONSEJO MUNICIPAL DEL ESTADO BOLIVARIANO DE MIRANDA', '10', '1'),
		  array('476', 'Gobierno Bolivariano de Aragua', '15', '1'),
		  array('477', 'Consejo Municipal del Municipio Carrizal', '10', '1'),
		  array('478', 'Consejo Municipal de Maturin del Estado Monagas', '10', '1'),
		  array('479', 'Ministerio del Poder Popular para la Mujer y la Igualdad de Genero', '1', '1'),
		  array('480', 'Servicio Autonomo de la Propiedad Intelectual', '4', '1'),
		  array('481', 'Contraloria Municipal del Municipio Piritu', '8', '1')

        );
       	foreach ($dato4 as $v) {
        DB::table('entities')->insert([
           'id' => $v[0],
           'name' => $v[1],
           'category_id' => $v[2],
           'user_id' => $v[3],

          ]); 
    	}
	
	}

}